dist: xenial
language: java
sudo: false
jdk:
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
install: true
script:
    if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ]; then
      mkdir -p xstream/profiles/coveralls;
      mkdir -p xstream-hibernate/profiles/coveralls;
      mvn -V -B -e clean package jacoco:report coveralls:report;
    else
      mvn -V -B -e clean package;
    fi
cache:
    directories:
    - $HOME/.m2
